# Eureka Discovery Server Configuration
server.port=8761

spring.application.name=discovery-server

#server không đăng ký với server khác
eureka.client.register-with-eureka=false
#server không lấy thông tin từ server khác
eureka.client.fetch-registry=false